<?php
$host="server.hr.lidl.net/fisk.hr.lidl.net"; // Host name
$username="korisnik"; // oracle user
$password="lozinka"; // oracle password
$store_black_list="'9999','9998','9996','9991'"; 
$hostmysql="localhost"; // Host name
$makro_user="mario"; //gama user
$makro_password="1234567";
$db_name="db"; // Database name
$hostwawi="server02.hr.lidl.net/waw.hr.lidl.net"; // Host name
$usernamewawi="korisnik2"; // oracle user
$passwordwawi="lozinka2"; // oracle password
?>
